# Generated by Django 3.1.2 on 2020-10-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='extra',
            field=models.TextField(null=True),
        ),
    ]
