# Generated by Django 3.1.2 on 2020-10-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shippingaddress_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
