# Generated by Django 3.1.2 on 2020-10-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='other',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printstyle',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Canvas', 'Canvas')], default='Paper', max_length=25),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='signature',
            field=models.CharField(choices=[('None', 'None'), ('Front', 'Front'), ('Back', 'Back')], default='None', max_length=25),
        ),
    ]
