# Generated by Django 3.1.2 on 2020-10-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shippingaddress_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='name2',
        ),
    ]
