# Generated by Django 3.1.2 on 2020-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='default_image',
            field=models.BooleanField(default=False),
        ),
    ]
