# Generated by Django 3.1.2 on 2020-10-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productimage_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
