# Generated by Django 3.1.2 on 2020-10-30 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expiry_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 10, 31, 12, 54, 42, 61893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='printstyle',
            field=models.CharField(choices=[('Canvas', 'Canvas'), ('Matte Paper', 'Matte Paper')], default='Canvas', max_length=25),
        ),
    ]
