# Generated by Django 3.1.2 on 2020-10-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201030_1326'),
        ('shop', '0011_auto_20201030_1824'),
    ]

    operations = [
    ]
