# Generated by Django 3.1.2 on 2020-11-05 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201103_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expiry_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 11, 6, 17, 31, 1, 113007, tzinfo=utc)),
        ),
    ]
