# Generated by Django 3.1.2 on 2020-11-15 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201105_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expiry_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 11, 16, 19, 46, 55, 975213, tzinfo=utc)),
        ),
    ]
